---
- name: Configure push notifications
  ansible.builtin.include_tasks:
    file: push.yml
  when: zulip_push_notifications
  tags: ['configure', 'zulip', 'push']

- name: Configure mail notifications
  ansible.builtin.include_tasks:
    file: mail.yml
  when: zulip_enable_mail
  tags: ['configure', 'zulip', 'mail']

- name: Configure GIPHY integration
  ansible.builtin.include_tasks:
    file: giphy.yml
  when: zulip_enable_giphy
  tags: ['configure', 'zulip', 'giphy']
