---
- name: Install pip requirements from list
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ pip_requirements }}"
  tags: ['zulip']

- name: Download zulip_installer
  ansible.builtin.get_url:
    url: "{{ zulip_installer }}"
    dest: "/tmp/zulip_installer-{{ zulip_version }}.tar.gz"
    mode: 0755
  tags: ['zulip']

- name: Extract downloaded installer
  ansible.builtin.unarchive:
    src: "/tmp/zulip_installer-{{ zulip_version }}.tar.gz"
    dest: /tmp/
    remote_src: true
  tags: ['zulip']

- name: Install Zulip and handle errors
  block:
    - name: Execute zulip_installer as root
      become: true
      become_user: root
      ansible.builtin.shell:
        cmd: >
          ./zulip-server-{{ zulip_version }}/scripts/setup/install
          {{ installer_args }}
        chdir: /tmp/
      register: installer_output
      changed_when: installer_output.rc != 0
      tags: ['zulip']

  rescue:
    - name: Set certbot_ssl to an empty string
      ansible.builtin.set_fact:
        certbot_ssl: ''

    - name: "Fix zulip redis-server: Can't open the log file"
      ansible.builtin.lineinfile:
        path: /lib/systemd/system/redis-server.service
        regexp: '^ReadOnlyDirectories=/'
        line: '#ReadOnlyDirectories=/'
        state: present
      when: development_environment | default(false) | bool

    - name: Reload systemd configuration and restart redis-server service
      ansible.builtin.systemd:
        daemon_reload: true
        name: redis-server
        state: restarted
      when: development_environment | default(false) | bool

    - name: Execute zulip_installer as root
      become: true
      become_user: root
      ansible.builtin.shell:
        cmd: >
          ./zulip-server-{{ zulip_version }}/scripts/setup/install
          {{ installer_args }}
        chdir: /tmp/
      register: installer_output
      changed_when: installer_output.rc != 0
      tags: ['zulip']

- name: Regenerate realm creation link
  become: true
  become_user: zulip
  ansible.builtin.command:
    cmd: ./manage.py generate_realm_creation_link
    chdir: /home/zulip/deployments/current
    executable: /bin/bash
  register: realm_creation_link_output
  changed_when: false

- name: Display realm creation link
  ansible.builtin.debug:
    msg: >
      "Realm creation link: {{ realm_creation_link_output.stdout |
       regex_replace('\x1b\\[[0-9;]*[a-zA-Z]', '') }}"
