---
- name: "Configure outgoing email server"
  ansible.builtin.replace:
    path: /etc/zulip/settings.py
    regexp: '# EMAIL_HOST = "smtp.example.com"'
    replace: 'EMAIL_HOST = "{{ zulip_smtp_server }}"'
  tags: ['zulip', 'email']

- name: "Configure outgoing email user"
  ansible.builtin.replace:
    path: /etc/zulip/settings.py
    regexp: '# EMAIL_HOST_USER = ""'
    replace: 'EMAIL_HOST_USER = "{{ zulip_email_user }}"'
  tags: ['zulip', 'email']

- name: "Configure outgoing email password"
  ansible.builtin.lineinfile:
    path: /etc/zulip/zulip-secrets.conf
    regexp: '^email_password.*$'
    line: email_password = {{ zulip_email_password }}
    create: true
    owner: zulip
    group: zulip
    mode: '0640'
  become_user: zulip
  notify: restart zulip server
  tags: ['zulip', 'email']
