---
# tasks file for zulip_role

- name: Download zulip_installer
  get_url:
    url: "{{ ansible_installer }}"
    dest: /tmp/zulip_installer.tar.gz
    mode: 0755
  tags: ['zulip']

- name: Extract downloaded installer
  tar:
    src: /tmp/zulip_installer.tar.gz
    dest: /tmp/
    mode: 0755
  tags: ['zulip']


- name: Execute zulip_installer with root
  become: true
  become_user: root
  shell: ./zulip-server-*/scripts/setup/install --certbot --hostname={{ host_name }} --email={{ email }}
  tags: ['zulip']