---
# tasks file for zulip_role

- name: Certbot tasks
  ansible.builtin.import_tasks: certbot.yml
  when: not development_enviroment
  tags: ['certbot', 'zulip']


# If zulip_realms_exist update else install
- name: Install Zulip
  ansible.builtin.import_tasks: install.yml
  tags: ['zulip']


- name: Configure Zulip
  ansible.builtin.import_tasks: configure.yml
  tags: ['zulip']
