---
# tasks file for zulip_role

- name: Download zulip_installer
  ansible.builtin.get_url:
    url: "{{ ansible_installer }}"
    dest: /tmp/zulip_installer.tar.gz
    mode: 0755
  tags: ['zulip']

- name: Extract downloaded installer
  ansible.builtin.unarchive:
    src: /tmp/zulip_installer.tar.gz
    dest: /tmp/
    remote_src: true
  tags: ['zulip']

- name: Check if certbot is installed
  ansible.builtin.package:
    name: certbot
    state: present
  check_mode: true
  register: certbot_check
  when: not development_enviroment

- name: Certbot tasks
  ansible.builtin.import_tasks: certbot.yml
  when: not development_enviroment and not certbot_check
  tags: ['certbot', 'zulip']

- name: Execute zulip_installer as root
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: ./zulip-server-*/scripts/setup/install {{ installer_args }}
    chdir: /tmp/
  register: installer_output
  changed_when: installer_output.rc != 0
  tags: ['zulip']

- name: Configure push notifications
  include_tasks:
    file: push.yml
  when: zulip_push_notifications
  tags: ['zulip', 'push']

- name: Configure mail notifications
  include_tasks:
    file: mail.yml
  when: zulip_enable_mail
  tags: ['zulip', 'mail']
