---
# tasks file for zulip_role

- name: Certbot tasks
  ansible.builtin.import_tasks: certbot.yml
  when: not development_enviroment
  tags: ['certbot', 'zulip']

# Check if a company is configured
- name: Check Zulip state
  ansible.builtin.import_tasks: check.yml
  tags: ['zulip']

# If zulip_realms_exist update else install
- name: Install Zulip
  ansible.builtin.import_tasks: install.yml
  when: not zulip_realms_exist
  tags: ['zulip']

- name: Update Zulip
  ansible.builtin.import_tasks: update.yml
  when: zulip_realms_exist
  tags: ['zulip']

- name: Configure Zulip
  ansible.builtin.import_tasks: configure.yml
  tags: ['configure', 'zulip']
