---
# tasks file for zulip_role

- name: Download zulip_installer
  ansible.builtin.get_url:
    url: "{{ ansible_installer }}"
    dest: /tmp/zulip_installer.tar.gz
    mode: 0755
  tags: ['zulip']

- name: Extract downloaded installer
  ansible.builtin.unarchive:
    src: /tmp/zulip_installer.tar.gz
    dest: /tmp/
    remote_src: true
  tags: ['zulip']

- name: Set command line args for installer
  ansible.builtin.set_fact:
    installer_args: "--self-signed-cert"
  register: installer_args
  when: development_enviroment

- name: Set command line args for installer
  ansible.builtin.set_fact:
    installer_args: "--certbot --email={{ email }}"
  register: installer_args
  when: not development_enviroment


- name: Execute zulip_installer as root
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: |
     ./zulip-server-*/scripts/setup/install
     --hostname={{ host_name }} {{ installer_args }}
    chdir: /tmp/
  register: installer_output
  changed_when: installer_output.rc != 0
  tags: ['zulip']
