---
- name: "Configure push notifications"
  ansible.builtin.replace:
    path: /etc/zulip/settings.py
    regexp: '^(#)?\s*PUSH_NOTIFICATION_BOUNCER_URL\s*=.*$"'
    replace: 'PUSH_NOTIFICATION_BOUNCER_URL = "{{ zulip_push_bouncer_url }}"'
  notify: "apply push conf"
  when: zulip_push_notifications
  tags: ['zulip', 'push']
