---
- name: Configuring push notifications
  listen: apply push conf
  expect:
    command: /home/zulip/deployments/current/manage.py register_server
    responses:
      (?i)Terms: "Y"
  notify: restart zulip server
  become: true
  become_user: zulip

- name: Restart zulip server
  listen: restart zulip server
  command: /home/zulip/deployments/current/scripts/restart-server
  become: true
  become_user: zulip
