name: Ansible Lint
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        id: lint
        uses: ansible-actions/ansible-lint-action@v1.0.3
        continue-on-error: true
        with:
          target: "./"

      - name: Show warning if ansible-lint fails
        if: steps.lint.outcome == 'failure'
        run: echo "::warning ::Ansible Lint found issues, but the workflow continues."
