name: Ansible Lint
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible-actions/ansible-lint-action@v1.0.3
        with:
          target: "./"
